/** @type {import('tailwindcss').Config} */
module.exports = {
  content: [
    './pages/**/*.{js,ts,jsx,tsx,mdx}',
    './components/**/*.{js,ts,jsx,tsx,mdx}',
    './app/**/*.{js,ts,jsx,tsx,mdx}',
  ],
  darkMode: 'class',
  theme: {
    extend: {
      colors: {
        'secondary-container': '#fe9383',
        'outline': '#8e706b',
        'tertiary': '#00178d',
        'on-error-container': '#93000a',
        'tertiary-fixed': '#dfe0ff',
        'surface-dim': '#dbdad8',
        'on-tertiary-container': '#9ea9ff',
        'error-container': '#ffdad6',
        'primary-fixed': '#ffdad4',
        'on-primary': '#ffffff',
        'on-primary-container': '#ff907f',
        'surface-container-high': '#eae8e6',
        'tertiary-fixed-dim': '#bcc3ff',
        'on-secondary': '#ffffff',
        'on-secondary-container': '#772a20',
        'surface-bright': '#fbf9f7',
        'inverse-surface': '#30302f',
        'on-primary-fixed-variant': '#920703',
        'on-tertiary-fixed': '#000d60',
        'surface-tint': '#b52619',
        'surface-container': '#efedec',
        'on-tertiary': '#ffffff',
        'secondary-fixed': '#ffdad4',
        'primary-fixed-dim': '#ffb4a8',
        'on-surface': '#1b1c1b',
        'surface-container-lowest': '#ffffff',
        'on-background': '#1b1c1b',
        'background': '#fbf9f7',
        'inverse-primary': '#ffb4a8',
        'surface-variant': '#e4e2e0',
        'on-secondary-fixed-variant': '#7b2d23',
        'on-tertiary-fixed-variant': '#0d2ccc',
        'surface-container-highest': '#e4e2e0',
        'surface-container-low': '#f5f3f1',
        'inverse-on-surface': '#f2f0ee',
        'on-primary-fixed': '#410000',
        'on-surface-variant': '#5a403c',
        'primary': '#610000',
        'secondary-fixed-dim': '#ffb4a8',
        'outline-variant': '#e3beb8',
        'error': '#ba1a1a',
        'on-error': '#ffffff',
        'surface': '#fbf9f7',
        'on-secondary-fixed': '#400201',
        'tertiary-container': '#0025c8',
        'primary-container': '#8b0000',
        'secondary': '#9a4438',
      },
      fontFamily: {
        headline: ['Manrope', 'sans-serif'],
        body: ['Inter', 'sans-serif'],
        label: ['Inter', 'sans-serif'],
      },
      borderRadius: {
        DEFAULT: '0.125rem',
        lg: '0.25rem',
        xl: '0.5rem',
      },
    },
  },
  plugins: [
    require('@tailwindcss/forms'),
  ],
}
